
/var/log/fantastic_probe.log
/var/log/fantastic_probe_errors.log
{
    size 1M

    rotate 1

    compress

    delaycompress

    missingok

    notifempty

    create 644 root root

    dateext
    dateformat -%Y%m%d-%s

    postrotate
        # systemctl reload fantastic-probe.timer 2>/dev/null || true
    endscript
}
